### PR TITLE
add Icons and remove pseudo element from the css to Improve the Accessibility.

### PR DESCRIPTION
**Pull request by hussnain2**
…sibility.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @hussnain2! I've created [OSPR-3941](https://openedx.atlassian.net/browse/OSPR-3941) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by hussnain2** [comment]
@msaqib52 @murad-hubib Please review.

**Comment by nasirhjafri** [comment]
@hussnain2 Tests won't run on a PR from forked repo.

**Comment by hussnain2** [comment]
SO I need to Get Access for Open_edx to get these changes done with tests @nasirhjafri ?

CC: @murad-hubib

**Comment by natabene** [comment]
This Xblock only exists in edx-solutions, it doesn't exist in https://github.com/edx. @nasirhjafri You will not need edX review to merge, correct?

**Comment by hussnain2** [comment]
Hi @natabene Please ignore this PR, as we have been created another PR by getting Fork from open-Edx

CC: @murad-hubib @nasirhjafri

**Pull request closed without merging**
