### PR TITLE
BB-1073: Set up CI tests

### PR DESCRIPTION
**Pull request by giovannicimolin**
This PR sets up CI tests for this repo. The checks ran with these checks are:
1. Unit tests
2. Code quality tests

Until we get a code code quality, we should leave only the **unit test** as required for merging.

**Testing instructions:**
1. Check the tox and Travis configuration files.
2. Test locally with `tox`:
```
pip install tox
tox
```
3. Check if the CI `tests` container is green.

**Reviewers:**
- [ ] @xitij2000

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @giovannicimolin! I've created [OSPR-3325](https://openedx.atlassian.net/browse/OSPR-3325) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by giovannicimolin** [comment]
@natabene Can you enable CircleCI for this repo? I just realized that `edx-solutions` uses CircleCI and not Travis. You can do that here: https://circleci.com/add-projects/gh/edx-solutions. 

Thanks!

**Comment by natabene** [comment]
@giovannicimolin here you go

**Comment by natabene** [comment]
@giovannicimolin Is this what you needed?

**Comment by natabene** [comment]
@giovannicimolin Actually, I am getting this in CircleCI: Service alert: Your project references CircleCI 1.0 or it has no configuration. CircleCI 1.0 and projects without configuration files are no longer supported. You must update your project to use CircleCI 2.0 configuration to continue. Learn more.

**Comment by giovannicimolin** [comment]
@natabene We're getting that because we don't have any configuration for Circle in the main repository yet.  That should be fixed when this PR is merged.

I ended up missing a step in order to correctly configure CircleCI on this repo, we'll need to add a Deploy Key to this repository. This is the guide: https://developer.github.com/v3/guides/managing-deploy-keys/#setup-2. Feel free to ask any questions related to this, or maybe create a task for someone with admin access to the repo to set up.

For now, I added a personal access token from my account and the CI runs will work, but this is a temporary solution.

**Comment by giovannicimolin** [comment]
@xitij2000 This is ready for review.

**Comment by giovannicimolin** [comment]
@natabene Do you have any news on the repo configuration? Just so I can keep a tab on it and update the configuration when the deploy key is created.

**Comment by natabene** [comment]
> https://developer.github.com/v3/guides/managing-deploy-keys/#setup-2

@nedbat Is this something you would be able to help me with?

**Comment by natabene** [comment]
@giovannicimolin We are trying to figure this out, please stay tuned.

**Comment by giovannicimolin** [comment]
@natabene I'm keeping a tab on this. Ping me if you need any help :)

**Comment by natabene** [comment]
@giovannicimolin Do you still need this? If yes, it might be easier for you and me to set up a screensharing session to complete this.

**Comment by xitij2000** [comment]
@natabene  Yup, we'd still like to set up CI support for this and possibly other XBlocks. So would be nice to have a process in place for this. 
CC: @giovannicimolin

**Comment by natabene** [comment]
@xitij2000  Got it, do you think we can do a screen sharing session tomorrow? I might have the necessary access level, but not sure what the steps are. Maybe you can guide me.

**Comment by xitij2000** [comment]
I think @giovannicimolin would be better suited for that! I don't know the steps myself. I have asked him, and he should chime in with his availability.

**Comment by giovannicimolin** [comment]
@natabene I ended up missing your first ping on my email backlog. 

Can you try going in https://circleci.com/gh/edx-solutions/xblock-image-explorer/edit#checkout and clicking on **Create and add Deploy key** if the button is available?
It should work if you have administrative permissions on the repository. If that doesn't work I'm not really sure of what can be done, as I used the exact same process on my personal repositories.

In any case, the CI is working with my own keys for now, but we should provide it with proper credentials.

**Comment by natabene** [comment]
@giovannicimolin Tried, but I only see "Add Deploy Key". Attached is screenshot of my view. 
screencapture-circleci-gh-edx-solutions-xblock-image-explorer-edit-2019-06-05-13_27_12

**Comment by giovannicimolin** [comment]
@natabene Can you try it? I think it change a little bit depending if it's an organization or a personal repository.

**Comment by natabene** [comment]
@giovannicimolin Please remind me, did we sort this out?

**Comment by giovannicimolin** [comment]
@natabene We did sort this out. You had to go into circleci settings and add a deploy key because I didn't had the necessary permissions.

**Pull request merged**
